export const weatherRecipeProfiles = {
  breakfast: {
    Hot: [
      { query: "smoothie bowl" },
      { query: "overnight oats" },
      { query: "chia pudding" },
      { query: "yogurt parfait" },
      { query: "fruit bowl" },
      { query: "avocado toast" },
      { query: "açaí bowl" },
      { query: "mango smoothie" },
      { query: "granola bowl" },
      { query: "berry smoothie" },
      { query: "cold brew smoothie" },
      { query: "coconut yogurt bowl" }
    ],
    Warm: [
      { query: "eggs benedict" },
      { query: "shakshuka" },
      { query: "breakfast burrito" },
      { query: "huevos rancheros" },
      { query: "breakfast tacos" },
      { query: "smoked salmon bagel" },
      { query: "omelette" },
      { query: "breakfast quesadilla" },
      { query: "egg toast" },
      { query: "poached eggs" },
      { query: "breakfast wrap" },
      { query: "frittata" }
    ],
    Average: [
      { query: "pancakes" },
      { query: "french toast" },
      { query: "waffles" },
      { query: "breakfast sandwich" },
      { query: "quiche" },
      { query: "scrambled eggs" },
      { query: "muffins" },
      { query: "crepes" },
      { query: "breakfast hash" },
      { query: "bagel" },
      { query: "breakfast strata" },
      { query: "croque monsieur" }
    ],
    Cool: [
      { query: "baked oats" },
      { query: "dutch baby pancake" },
      { query: "oatmeal" },
      { query: "breakfast skillet" },
      { query: "baked egg cups" },
      { query: "sweet potato breakfast bowl" },
      { query: "porridge" },
      { query: "savory oatmeal" },
      { query: "warm grain bowl" },
      { query: "breakfast casserole" },
      { query: "pumpkin bread" },
      { query: "apple cinnamon muffins" }
    ],
    Cold: [
      { query: "baked oatmeal" },
      { query: "congee" },
      { query: "cinnamon rolls" },
      { query: "cornmeal porridge" },
      { query: "hot quinoa porridge" },
      { query: "savory bread pudding" },
      { query: "slow cooker oatmeal" },
      { query: "egg and potato casserole" },
      { query: "gingerbread oatmeal" },
      { query: "loaded breakfast bake" },
      { query: "scones" },
      { query: "steamed egg custard" }
    ]
  },

  lunch: {
    Hot: [
      { query: "cold noodle salad" },
      { query: "gazpacho" },
      { query: "ceviche" },
      { query: "poke bowl" },
      { query: "chilled soba" },
      { query: "watermelon salad" },
      { query: "spring rolls" },
      { query: "pasta salad" },
      { query: "grain salad" },
      { query: "nicoise salad" },
      { query: "mango avocado salad" },
      { query: "chilled shrimp salad" }
    ],
    Warm: [
      { query: "grilled chicken wrap" },
      { query: "fish tacos" },
      { query: "teriyaki bowl" },
      { query: "BBQ sandwich" },
      { query: "falafel wrap" },
      { query: "grilled veggie panini" },
      { query: "shrimp rice bowl" },
      { query: "grilled salmon salad" },
      { query: "grilled chicken salad" },
      { query: "turkey sandwich" },
      { query: "flatbread" },
      { query: "rice paper rolls" }
    ],
    Average: [
      { query: "club sandwich" },
      { query: "quesadilla" },
      { query: "egg salad sandwich" },
      { query: "tuna melt" },
      { query: "tomato soup" },
      { query: "rice bowl" },
      { query: "noodle bowl" },
      { query: "burrito bowl" },
      { query: "gyro" },
      { query: "BLT" },
      { query: "fried noodles" },
      { query: "lentil wrap" }
    ],
    Cool: [
      { query: "lentil soup" },
      { query: "butternut squash soup" },
      { query: "chicken noodle soup" },
      { query: "French onion soup" },
      { query: "tomato bisque" },
      { query: "broccoli soup" },
      { query: "minestrone" },
      { query: "roasted vegetable bowl" },
      { query: "potato soup" },
      { query: "mushroom soup" },
      { query: "ramen" },
      { query: "miso soup" }
    ],
    Cold: [
      { query: "chili" },
      { query: "clam chowder" },
      { query: "pot pie" },
      { query: "split pea soup" },
      { query: "ham and bean soup" },
      { query: "white bean soup" },
      { query: "broccoli cheddar soup" },
      { query: "goulash" },
      { query: "baked potato soup" },
      { query: "chicken and rice soup" },
      { query: "black bean soup" },
      { query: "corn chowder" }
    ]
  },

  dinner: {
    Hot: [
      { query: "cold sesame noodles" },
      { query: "sashimi" },
      { query: "summer rolls" },
      { query: "smoked salmon platter" },
      { query: "mezze platter" },
      { query: "cold poached chicken" },
      { query: "chilled avocado soup" },
      { query: "tuna tartare" },
      { query: "prawn cocktail" },
      { query: "cold tofu salad" },
      { query: "charcuterie board" },
      { query: "caprese salad" }
    ],
    Warm: [
      { query: "grilled salmon" },
      { query: "shrimp scampi" },
      { query: "chicken tacos" },
      { query: "grilled steak" },
      { query: "seafood pasta" },
      { query: "Thai basil chicken" },
      { query: "grilled veggie bowl" },
      { query: "chicken fajitas" },
      { query: "fried rice" },
      { query: "roasted chicken" },
      { query: "teriyaki" },
      { query: "stir fry" }
    ],
    Average: [
      { query: "pasta bolognese" },
      { query: "stuffed peppers" },
      { query: "enchiladas" },
      { query: "baked salmon" },
      { query: "chicken marsala" },
      { query: "sheet pan chicken" },
      { query: "meatballs" },
      { query: "pork tenderloin" },
      { query: "eggplant parmesan" },
      { query: "one pot chicken" },
      { query: "pork chops" },
      { query: "tikka masala" }
    ],
    Cool: [
      { query: "roast chicken" },
      { query: "creamy pasta" },
      { query: "mushroom risotto" },
      { query: "stuffed pasta" },
      { query: "baked ziti" },
      { query: "chicken pot pie" },
      { query: "braised pork" },
      { query: "gnocchi" },
      { query: "braised short ribs" },
      { query: "lentil stew" },
      { query: "curry" },
      { query: "butternut squash soup" }
    ],
    Cold: [
      { query: "beef stew" },
      { query: "lasagna" },
      { query: "shepherds pie" },
      { query: "beef bourguignon" },
      { query: "pot roast" },
      { query: "osso buco" },
      { query: "mac and cheese" },
      { query: "lamb shank" },
      { query: "pasta e fagioli" },
      { query: "chicken cacciatore" },
      { query: "cassoulet" },
      { query: "pho" }
    ]
  }
};